In [2]:
# !unzip data.zip

In [3]:
# !pip3 install --upgrade pandas

In [1]:
import warnings
warnings.filterwarnings('ignore')

# Входные данные

In [60]:
import pandas as pd
import os
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder
from sklearn.impute import SimpleImputer

PATH_TO_DATA = 'data'

In [128]:
df_train = pd.read_csv(os.path.join(PATH_TO_DATA, 'orange_small_churn_data.train'))
labels = pd.read_csv(os.path.join(PATH_TO_DATA, 'orange_small_churn_labels.train'), header=None, squeeze=True)
df_train['target'] = labels

In [129]:
# cols_all = df_train_part.columns
# cols_nan = df_train_part.loc[:, df_train.isna().all()].columns
# df_num = df_train_part.select_dtypes(exclude='object')
# df_cat = df_train_part.select_dtypes(include='object')

In [130]:
df_train.shape

(40000, 231)

Отделим hold-out dataset

In [204]:
df_train_part, df_ho = train_test_split(df_train, test_size=5000)

In [205]:
df_train_part

Var1  Var2  Var3  Var4      Var5    Var6  Var7  Var8  Var9     Var10  \
7330    NaN   NaN   NaN   NaN  196730.0     NaN   NaN   NaN   NaN  248805.0   
17141   NaN   NaN   NaN   NaN       NaN   511.0   0.0   NaN   NaN       NaN   
400     NaN   NaN   NaN   NaN       NaN   854.0   7.0   NaN   NaN       NaN   
16674   NaN   NaN   NaN   NaN       NaN    63.0   0.0   NaN   NaN       NaN   
16547   0.0   NaN   NaN   NaN       NaN     NaN   NaN   NaN  12.0       NaN   
...     ...   ...   ...   ...       ...     ...   ...   ...   ...       ...   
11407   NaN   NaN   NaN   NaN       NaN  1036.0   7.0   NaN   NaN       NaN   
11202   NaN   NaN   NaN   NaN       NaN  1533.0   7.0   NaN   NaN       NaN   
37440   NaN   NaN   NaN   NaN       NaN    63.0   0.0   NaN   NaN       NaN   
3584    NaN   NaN   NaN   NaN       NaN   777.0   7.0   NaN   NaN       NaN   
26223   NaN   NaN   NaN   NaN       NaN    21.0   0.0   NaN   NaN       NaN   

       ...   Var222      Var223  Var224  Var225  Var226   Var227  \
7330   ...  Tn9Rusu  LM8l689qOp     NaN     NaN    uWr3     RAYp   
17141  ...  mf4VZtl  LM8l689qOp     NaN     NaN    Xa3G  nIGXDli   
400    ...  Hcoaiae  LM8l689qOp     NaN    ELof    Qcbd     RAYp   
16674  ...  MvPiuXx  jySVZNlOJy     NaN    kG3k    WqMG     RAYp   
16547  ...  utQDN1n  LM8l689qOp     NaN     NaN    FSa2     RAYp   
...    ...      ...         ...     ...     ...     ...      ...   
11407  ...  catzS2D  LM8l689qOp     NaN     NaN    Qcbd     ZI9m   
11202  ...  4sF7qqc  LM8l689qOp     NaN     NaN    FSa2     RAYp   
37440  ...  KcC08Cl  LM8l689qOp     NaN     NaN    Qu4f     RAYp   
3584   ...  catzS2D  jySVZNlOJy     NaN    ELof    Qu4f     ZI9m   
26223  ...  8dbQowC  LM8l689qOp     NaN     NaN    WqMG     RAYp   

                    Var228  Var229  Var230  target  
7330         F2FyR07IdsN7I     NaN     NaN      -1  
17141        F2FyR07IdsN7I     NaN     NaN      -1  
400          F2FyR07IdsN7I    am7c     NaN      -1  
16674              55YFVY9    mj86     NaN      -1  
16547        F2FyR07IdsN7I     NaN     NaN      -1  
...                    ...     ...     ...     ...  
11407  TCU50_Yjmm6GIBZ0lL_     NaN     NaN      -1  
11202        F2FyR07IdsN7I     NaN     NaN      -1  
37440        F2FyR07IdsN7I     NaN     NaN      -1  
3584                  NoEd    mj86     NaN      -1  
26223        F2FyR07IdsN7I     NaN     NaN       1  

[35000 rows x 231 columns]

In [64]:
# df_ho.to_csv(os.path.join(PATH_TO_DATA, 'hold_out_dataset.csv'))

- ROC AUC
- precision, recall, f1, log, accuracy
- 5 фолдов, stratified k-fold, shuffled

In [206]:
df_train_part.dropna(axis=1, how='all', inplace=True)
cols = df_train_part.drop('target', axis=1).columns

In [207]:
%%time
si = SimpleImputer(strategy='most_frequent')
df_train_part = si.fit_transform(df_train_part.drop('target', axis=1))
df_train_part = pd.DataFrame(df_train_part, columns=cols)

CPU times: user 1.53 s, sys: 392 ms, total: 1.93 s
Wall time: 1.96 s


In [208]:
df_train_part

Var1 Var2 Var3 Var4      Var5    Var6 Var7  Var9     Var10 Var11  ...  \
0      0.0  0.0  0.0  0.0  196730.0     0.0  7.0   0.0  248805.0   8.0  ...   
1      0.0  0.0  0.0  0.0       0.0   511.0  0.0   0.0       0.0   8.0  ...   
2      0.0  0.0  0.0  0.0       0.0   854.0  7.0   0.0       0.0   8.0  ...   
3      0.0  0.0  0.0  0.0       0.0    63.0  0.0   0.0       0.0   8.0  ...   
4      0.0  0.0  0.0  0.0       0.0     0.0  7.0  12.0       0.0   8.0  ...   
...    ...  ...  ...  ...       ...     ...  ...   ...       ...   ...  ...   
34995  0.0  0.0  0.0  0.0       0.0  1036.0  7.0   0.0       0.0   8.0  ...   
34996  0.0  0.0  0.0  0.0       0.0  1533.0  7.0   0.0       0.0   8.0  ...   
34997  0.0  0.0  0.0  0.0       0.0    63.0  0.0   0.0       0.0   8.0  ...   
34998  0.0  0.0  0.0  0.0       0.0   777.0  7.0   0.0       0.0   8.0  ...   
34999  0.0  0.0  0.0  0.0       0.0    21.0  0.0   0.0       0.0   8.0  ...   

        Var220   Var221   Var222      Var223 Var224 Var225 Var226   Var227  \
0      gSt6V3V     oslk  Tn9Rusu  LM8l689qOp   4n2X   ELof   uWr3     RAYp   
1      srGC6dX  d0EEeJi  mf4VZtl  LM8l689qOp   4n2X   ELof   Xa3G  nIGXDli   
2      tzpmIK9     oslk  Hcoaiae  LM8l689qOp   4n2X   ELof   Qcbd     RAYp   
3      yALeV2F     oslk  MvPiuXx  jySVZNlOJy   4n2X   kG3k   WqMG     RAYp   
4      mTPRwBA     oslk  utQDN1n  LM8l689qOp   4n2X   ELof   FSa2     RAYp   
...        ...      ...      ...         ...    ...    ...    ...      ...   
34995  4UxGlow     zCkv  catzS2D  LM8l689qOp   4n2X   ELof   Qcbd     ZI9m   
34996  Xei0nTz     oslk  4sF7qqc  LM8l689qOp   4n2X   ELof   FSa2     RAYp   
34997  bDfR2zc     oslk  KcC08Cl  LM8l689qOp   4n2X   ELof   Qu4f     RAYp   
34998  4UxGlow  QKW8DRm  catzS2D  jySVZNlOJy   4n2X   ELof   Qu4f     ZI9m   
34999  ALJYlW4     oslk  8dbQowC  LM8l689qOp   4n2X   ELof   WqMG     RAYp   

                    Var228 Var229  
0            F2FyR07IdsN7I   am7c  
1            F2FyR07IdsN7I   am7c  
2            F2FyR07IdsN7I   am7c  
3                  55YFVY9   mj86  
4            F2FyR07IdsN7I   am7c  
...                    ...    ...  
34995  TCU50_Yjmm6GIBZ0lL_   am7c  
34996        F2FyR07IdsN7I   am7c  
34997        F2FyR07IdsN7I   am7c  
34998                 NoEd   mj86  
34999        F2FyR07IdsN7I   am7c  

[35000 rows x 212 columns]

In [213]:
oe = OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)

In [214]:
df_train_part = oe.fit_transform(df_train_part)
df_train_part = pd.DataFrame(df_train_part, columns=cols)

In [215]:
df_train_part['Var229'].value_counts()

0.0    28086
1.0     6857
3.0       30
2.0       27
Name: Var229, dtype: int64

In [216]:
df_train_part

Var1  Var2  Var3  Var4   Var5   Var6  Var7  Var9  Var10  Var11  ...  \
0       0.0   0.0   0.0   0.0  171.0    0.0   1.0   0.0  134.0    0.0  ...   
1       0.0   0.0   0.0   0.0    0.0   73.0   0.0   0.0    0.0    0.0  ...   
2       0.0   0.0   0.0   0.0    0.0  122.0   1.0   0.0    0.0    0.0  ...   
3       0.0   0.0   0.0   0.0    0.0    9.0   0.0   0.0    0.0    0.0  ...   
4       0.0   0.0   0.0   0.0    0.0    0.0   1.0   6.0    0.0    0.0  ...   
...     ...   ...   ...   ...    ...    ...   ...   ...    ...    ...  ...   
34995   0.0   0.0   0.0   0.0    0.0  148.0   1.0   0.0    0.0    0.0  ...   
34996   0.0   0.0   0.0   0.0    0.0  219.0   1.0   0.0    0.0    0.0  ...   
34997   0.0   0.0   0.0   0.0    0.0    9.0   0.0   0.0    0.0    0.0  ...   
34998   0.0   0.0   0.0   0.0    0.0  111.0   1.0   0.0    0.0    0.0  ...   
34999   0.0   0.0   0.0   0.0    0.0    3.0   0.0   0.0    0.0    0.0  ...   

       Var220  Var221  Var222  Var223  Var224  Var225  Var226  Var227  Var228  \
0      2606.0     4.0  1781.0     0.0     0.0     0.0    19.0     2.0     7.0   
1      3251.0     3.0  2892.0     0.0     0.0     0.0    13.0     4.0     7.0   
2      3342.0     4.0  1023.0     0.0     0.0     0.0     9.0     2.0     7.0   
3      3561.0     4.0  1354.0     3.0     0.0     1.0    12.0     2.0     2.0   
4      2949.0     4.0  3407.0     0.0     0.0     0.0     7.0     2.0     7.0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
34995   310.0     6.0  2336.0     0.0     0.0     0.0     9.0     3.0    13.0   
34996  2003.0     4.0   227.0     0.0     0.0     0.0     7.0     2.0     7.0   
34997  2379.0     4.0  1196.0     0.0     0.0     0.0    10.0     2.0     7.0   
34998   310.0     2.0  2336.0     3.0     0.0     0.0    10.0     3.0     9.0   
34999   643.0     4.0   451.0     0.0     0.0     0.0    12.0     2.0     7.0   

       Var229  
0         0.0  
1         0.0  
2         0.0  
3         1.0  
4         0.0  
...       ...  
34995     0.0  
34996     0.0  
34997     0.0  
34998     1.0  
34999     0.0  

[35000 rows x 212 columns]

# Модель

In [18]:
from sklearn.model_selection import cross_val_score, StratifiedShuffleSplit
from sklearn.linear_model import RidgeClassifier, LogisticRegression, SGDClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import classification_report

In [19]:
X_train = df_train_part.drop('target', axis=1)
y_train = df_train_part['target']
cv = StratifiedShuffleSplit(n_splits=7)  # random_state=2179

In [20]:
X_tr, X_val, y_tr, y_val = train_test_split(X_train, y_train)

## LogisticRegression

In [21]:
cross_val_score(estimator=LogisticRegression(random_state=2179), X=X_train, y=y_train, cv=cv, n_jobs=-1, scoring='roc_auc')

array([0.57725427, 0.55594286, 0.57797953, 0.54723565, 0.57610562,
       0.52974359, 0.54548086])

In [186]:
cross_val_score(estimator=LogisticRegression(random_state=2179), X=X_train, y=y_train, cv=cv, n_jobs=-1, scoring='f1')

array([0., 0., 0., 0., 0., 0., 0.])

In [185]:
cross_val_score(estimator=LogisticRegression(random_state=2179), X=X_train, y=y_train, cv=cv, n_jobs=-1, scoring='precision')

array([0., 0., 0., 0., 0., 0., 0.])

In [187]:
cross_val_score(estimator=LogisticRegression(random_state=2179), X=X_train, y=y_train, cv=cv, n_jobs=-1, scoring='recall')

array([0., 0., 0., 0., 0., 0., 0.])

In [22]:
lr = LogisticRegression(random_state=2179)
lr.fit(X_tr, y_tr)
print(classification_report(y_val, lr.predict(X_val)))

              precision    recall  f1-score   support

         0.0       0.93      1.00      0.96      8100
         1.0       0.00      0.00      0.00       650

    accuracy                           0.93      8750
   macro avg       0.46      0.50      0.48      8750
weighted avg       0.86      0.93      0.89      8750



## RidgeClassifier

In [133]:
cross_val_score(estimator=RidgeClassifier(random_state=2179), X=X_train, y=y_train, cv=cv, n_jobs=-1, scoring='roc_auc')

array([0.69932539, 0.67954255, 0.64283239, 0.65054964, 0.68029251,
       0.68869466, 0.63930734])

In [188]:
cross_val_score(estimator=RidgeClassifier(random_state=2179), X=X_train, y=y_train, cv=cv, n_jobs=-1, scoring='f1')

array([0., 0., 0., 0., 0., 0., 0.])

In [189]:
cross_val_score(estimator=RidgeClassifier(random_state=2179), X=X_train, y=y_train, cv=cv, n_jobs=-1, scoring='precision')

array([0., 0., 0., 0., 0., 0., 0.])

In [190]:
cross_val_score(estimator=RidgeClassifier(random_state=2179), X=X_train, y=y_train, cv=cv, n_jobs=-1, scoring='recall')

array([0., 0., 0., 0., 0., 0., 0.])

In [182]:
rc = RidgeClassifier(random_state=2179)
rc.fit(X_tr, y_tr)
print(classification_report(y_val, rc.predict(X_val)))

              precision    recall  f1-score   support

         0.0       0.92      1.00      0.96      8069
         1.0       0.00      0.00      0.00       681

    accuracy                           0.92      8750
   macro avg       0.46      0.50      0.48      8750
weighted avg       0.85      0.92      0.88      8750



## SGDClassifier

In [135]:
cross_val_score(estimator=SGDClassifier(random_state=2179), X=X_train, y=y_train, cv=cv, n_jobs=-1, scoring='roc_auc')

array([0.47591317, 0.49309836, 0.53518244, 0.48979807, 0.48818341,
       0.44814456, 0.56209345])

In [191]:
cross_val_score(estimator=SGDClassifier(random_state=2179), X=X_train, y=y_train, cv=cv, n_jobs=-1, scoring='f1')

array([0.0798005 , 0.        , 0.        , 0.09958506, 0.        ,
       0.02649007, 0.        ])

In [184]:
cross_val_score(estimator=SGDClassifier(random_state=2179), X=X_train, y=y_train, cv=cv, n_jobs=-1, scoring='precision')

array([0.        , 0.10144928, 0.        , 0.        , 0.06802721,
       0.08219178, 0.        ])

In [192]:
cross_val_score(estimator=SGDClassifier(random_state=2179), X=X_train, y=y_train, cv=cv, n_jobs=-1, scoring='recall')

array([0.04214559, 0.03448276, 0.        , 0.02681992, 0.87356322,
       0.        , 0.        ])

In [183]:
sgdc = SGDClassifier(random_state=2179)
sgdc.fit(X_tr, y_tr)
print(classification_report(y_val, sgdc.predict(X_val)))

              precision    recall  f1-score   support

         0.0       0.95      0.13      0.23      8069
         1.0       0.08      0.92      0.15       681

    accuracy                           0.19      8750
   macro avg       0.52      0.53      0.19      8750
weighted avg       0.89      0.19      0.23      8750



### SGDClassifier log loss

In [136]:
cross_val_score(estimator=SGDClassifier(random_state=2179, loss='log'), X=X_train, y=y_train, cv=cv, n_jobs=-1, scoring='roc_auc')

array([0.48969161, 0.50299333, 0.45294596, 0.50918937, 0.47953995,
       0.50566905, 0.50738544])

In [193]:
cross_val_score(estimator=SGDClassifier(random_state=2179, loss='log'), X=X_train, y=y_train, cv=cv, n_jobs=-1, scoring='f1')

array([0.        , 0.        , 0.03519062, 0.11912226, 0.        ,
       0.13422819, 0.0075188 ])

In [194]:
cross_val_score(estimator=SGDClassifier(random_state=2179, loss='log'), X=X_train, y=y_train, cv=cv, n_jobs=-1, scoring='precision')

array([0.05793451, 0.13513514, 0.        , 0.        , 0.15584416,
       0.        , 0.        ])

In [195]:
cross_val_score(estimator=SGDClassifier(random_state=2179, loss='log'), X=X_train, y=y_train, cv=cv, n_jobs=-1, scoring='recall')

array([0.        , 0.        , 0.31800766, 0.0651341 , 0.56321839,
       0.        , 0.        ])

In [196]:
sgdc = SGDClassifier(random_state=2179, loss='log')
sgdc.fit(X_tr, y_tr)
print(classification_report(y_val, sgdc.predict(X_val)))

              precision    recall  f1-score   support

         0.0       0.93      0.85      0.89      8069
         1.0       0.11      0.21      0.14       681

    accuracy                           0.80      8750
   macro avg       0.52      0.53      0.52      8750
weighted avg       0.86      0.80      0.83      8750



## RandomForestClassifier

In [139]:
rfc = RandomForestClassifier(oob_score=True)

In [140]:
rfc.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=True, random_state=None,
                       verbose=0, warm_start=False)

In [142]:
rfc.oob_score_

0.9254

In [143]:
%%time
cross_val_score(estimator=RandomForestClassifier(random_state=2179), X=X_train, y=y_train, cv=cv, n_jobs=-1, scoring='roc_auc')

array([0.62168625, 0.67826442, 0.64490365, 0.67008052, 0.64507576,
       0.66127382, 0.65407527])

In [198]:
cross_val_score(estimator=RandomForestClassifier(random_state=2179), X=X_train, y=y_train, cv=cv, n_jobs=-1, scoring='f1')

array([0., 0., 0., 0., 0., 0., 0.])

In [199]:
cross_val_score(estimator=RandomForestClassifier(random_state=2179), X=X_train, y=y_train, cv=cv, n_jobs=-1, scoring='precision')

array([0., 0., 0., 0., 0., 0., 0.])

In [200]:
cross_val_score(estimator=RandomForestClassifier(random_state=2179), X=X_train, y=y_train, cv=cv, n_jobs=-1, scoring='recall')

array([0., 0., 0., 0., 0., 0., 0.])

In [201]:
rfc = RandomForestClassifier(random_state=2179)
rfc.fit(X_tr, y_tr)
print(classification_report(y_val, rfc.predict(X_val)))

              precision    recall  f1-score   support

         0.0       0.92      1.00      0.96      8069
         1.0       0.00      0.00      0.00       681

    accuracy                           0.92      8750
   macro avg       0.46      0.50      0.48      8750
weighted avg       0.85      0.92      0.88      8750



## GradientBoostingClassifier

In [145]:
%%time
cross_val_score(estimator=GradientBoostingClassifier(random_state=2179), X=X_train, y=y_train, cv=cv, n_jobs=-1, scoring='roc_auc')

CPU times: user 1.8 s, sys: 213 ms, total: 2.01 s
Wall time: 5min 4s


array([0.72750033, 0.73476867, 0.73284527, 0.70830834, 0.7215527 ,
       0.73489524, 0.72966326])

In [203]:
%%time
cross_val_score(estimator=GradientBoostingClassifier(random_state=2179), X=X_train, y=y_train, cv=cv, n_jobs=-1, scoring='f1')

CPU times: user 965 ms, sys: 116 ms, total: 1.08 s
Wall time: 5min 6s


array([0.01515152, 0.00763359, 0.        , 0.00754717, 0.01509434,
       0.        , 0.00749064])

In [204]:
%%time
cross_val_score(estimator=GradientBoostingClassifier(random_state=2179), X=X_train, y=y_train, cv=cv, n_jobs=-1, scoring='precision')

CPU times: user 970 ms, sys: 128 ms, total: 1.1 s
Wall time: 5min 8s


array([0.        , 0.33333333, 0.2       , 0.6       , 0.33333333,
       0.66666667, 0.25      ])

In [205]:
%%time
cross_val_score(estimator=GradientBoostingClassifier(random_state=2179), X=X_train, y=y_train, cv=cv, n_jobs=-1, scoring='recall')

CPU times: user 950 ms, sys: 125 ms, total: 1.08 s
Wall time: 5min 6s


array([0.00383142, 0.00383142, 0.00766284, 0.        , 0.01149425,
       0.        , 0.        ])

In [202]:
gbc = GradientBoostingClassifier(random_state=2179)
gbc.fit(X_tr, y_tr)
print(classification_report(y_val, gbc.predict(X_val)))

              precision    recall  f1-score   support

         0.0       0.92      1.00      0.96      8069
         1.0       0.50      0.00      0.01       681

    accuracy                           0.92      8750
   macro avg       0.71      0.50      0.48      8750
weighted avg       0.89      0.92      0.89      8750



# Тест

In [23]:
def write_to_submission_file(predicted_labels, out_file,
                             target='target', index_label="session_id"):
    # turn predictions into data frame and save as csv file
    predicted_df = pd.DataFrame(predicted_labels,
                                index = np.arange(1, predicted_labels.shape[0] + 1),
                                columns=[target])
    predicted_df.to_csv(out_file, index_label=index_label)

In [217]:
df_test = pd.read_csv(os.path.join(PATH_TO_DATA, 'orange_small_churn_test_data.csv'), index_col=0)
df_test

Var1  Var2  Var3  Var4  Var5    Var6  Var7  Var8  Var9  Var10  ...  \
ID                                                                   ...   
0      NaN   NaN   NaN   NaN   NaN  1225.0   7.0   NaN   NaN    NaN  ...   
1      NaN   NaN   NaN   NaN   NaN   896.0  14.0   NaN   NaN    NaN  ...   
2      NaN   NaN   NaN   NaN   NaN   791.0   7.0   NaN   NaN    NaN  ...   
3      NaN   NaN   NaN   NaN   NaN  2296.0   7.0   NaN   NaN    NaN  ...   
4      8.0   NaN   NaN   NaN   NaN     NaN   NaN   NaN  28.0    NaN  ...   
...    ...   ...   ...   ...   ...     ...   ...   ...   ...    ...  ...   
9995   NaN   NaN   NaN   NaN   NaN   714.0   7.0   NaN   NaN    NaN  ...   
9996   NaN   NaN   NaN   NaN   NaN   812.0   7.0   NaN   NaN    NaN  ...   
9997   NaN   NaN   NaN   NaN   NaN   819.0   7.0   NaN   NaN    NaN  ...   
9998   NaN   NaN   NaN   NaN   NaN     NaN   7.0   NaN   NaN    NaN  ...   
9999   NaN   NaN   NaN   NaN   NaN   868.0  14.0   NaN   NaN    NaN  ...   

      Var221   Var222      Var223  Var224  Var225  Var226  Var227  \
ID                                                                  
0       zCkv  APgdzOv  jySVZNlOJy     NaN    ELof    xb3V    6fzt   
1       oslk  IIvC99a  LM8l689qOp     NaN     NaN    xb3V    RAYp   
2       oslk  6YSocsg  LM8l689qOp     NaN    kG3k    rgKb    RAYp   
3       oslk  5nQ7A2G  jySVZNlOJy     NaN    kG3k    rgKb    RAYp   
4       oslk  MI8s5nE  LM8l689qOp     NaN     NaN    7P5s    RAYp   
...      ...      ...         ...     ...     ...     ...     ...   
9995    zCkv  P6pu4Vl  LM8l689qOp     NaN    ELof    xb3V    ZI9m   
9996    oslk  sXbT3Cb  LM8l689qOp     NaN    ELof    WqMG    RAYp   
9997    oslk  05jAV0N        M_8D     NaN    ELof    TNEC    RAYp   
9998    oslk  RDY7kpB  LM8l689qOp     NaN     NaN    uWr3    RAYp   
9999    oslk  gsLzpoz  jySVZNlOJy     NaN     NaN    me1d    RAYp   

                Var228  Var229  Var230  
ID                                      
0              Zy3gnGM     NaN     NaN  
1        F2FyR07IdsN7I     NaN     NaN  
2        F2FyR07IdsN7I    mj86     NaN  
3        F2FyR07IdsN7I    am7c     NaN  
4        F2FyR07IdsN7I     NaN     NaN  
...                ...     ...     ...  
9995  R4y5gQQWY8OodqDV    am7c     NaN  
9996           55YFVY9    mj86     NaN  
9997           55YFVY9    am7c     NaN  
9998           55YFVY9     NaN     NaN  
9999     F2FyR07IdsN7I    mj86     NaN  

[10000 rows x 230 columns]

In [218]:
df_test.drop(cols_nan, axis=1, inplace=True)

In [219]:
df_test = si.transform(df_test)
df_test = pd.DataFrame(df_test, columns=cols)

In [220]:
df_test

Var1 Var2 Var3 Var4 Var5    Var6  Var7  Var9 Var10 Var11  ...   Var220  \
0     0.0  0.0  0.0  0.0  0.0  1225.0   7.0   0.0   0.0   8.0  ...  UF16siJ   
1     0.0  0.0  0.0  0.0  0.0   896.0  14.0   0.0   0.0   8.0  ...  ot6oLzk   
2     0.0  0.0  0.0  0.0  0.0   791.0   7.0   0.0   0.0   8.0  ...  6VLNqhB   
3     0.0  0.0  0.0  0.0  0.0  2296.0   7.0   0.0   0.0   8.0  ...  tzp8jNM   
4     8.0  0.0  0.0  0.0  0.0     0.0   7.0  28.0   0.0   8.0  ...  EPImS85   
...   ...  ...  ...  ...  ...     ...   ...   ...   ...   ...  ...      ...   
9995  0.0  0.0  0.0  0.0  0.0   714.0   7.0   0.0   0.0   8.0  ...  ch2oGfM   
9996  0.0  0.0  0.0  0.0  0.0   812.0   7.0   0.0   0.0   8.0  ...  8d5YWu3   
9997  0.0  0.0  0.0  0.0  0.0   819.0   7.0   0.0   0.0   8.0  ...  WdPoLzk   
9998  0.0  0.0  0.0  0.0  0.0     0.0   7.0   0.0   0.0   8.0  ...  EMvv4zN   
9999  0.0  0.0  0.0  0.0  0.0   868.0  14.0   0.0   0.0   8.0  ...  bDIDFjT   

     Var221   Var222      Var223 Var224 Var225 Var226 Var227  \
0      zCkv  APgdzOv  jySVZNlOJy   4n2X   ELof   xb3V   6fzt   
1      oslk  IIvC99a  LM8l689qOp   4n2X   ELof   xb3V   RAYp   
2      oslk  6YSocsg  LM8l689qOp   4n2X   kG3k   rgKb   RAYp   
3      oslk  5nQ7A2G  jySVZNlOJy   4n2X   kG3k   rgKb   RAYp   
4      oslk  MI8s5nE  LM8l689qOp   4n2X   ELof   7P5s   RAYp   
...     ...      ...         ...    ...    ...    ...    ...   
9995   zCkv  P6pu4Vl  LM8l689qOp   4n2X   ELof   xb3V   ZI9m   
9996   oslk  sXbT3Cb  LM8l689qOp   4n2X   ELof   WqMG   RAYp   
9997   oslk  05jAV0N        M_8D   4n2X   ELof   TNEC   RAYp   
9998   oslk  RDY7kpB  LM8l689qOp   4n2X   ELof   uWr3   RAYp   
9999   oslk  gsLzpoz  jySVZNlOJy   4n2X   ELof   me1d   RAYp   

                Var228 Var229  
0              Zy3gnGM   am7c  
1        F2FyR07IdsN7I   am7c  
2        F2FyR07IdsN7I   mj86  
3        F2FyR07IdsN7I   am7c  
4        F2FyR07IdsN7I   am7c  
...                ...    ...  
9995  R4y5gQQWY8OodqDV   am7c  
9996           55YFVY9   mj86  
9997           55YFVY9   am7c  
9998           55YFVY9   am7c  
9999     F2FyR07IdsN7I   mj86  

[10000 rows x 212 columns]

In [221]:
df_train_part

Var1  Var2  Var3  Var4   Var5   Var6  Var7  Var9  Var10  Var11  ...  \
0       0.0   0.0   0.0   0.0  171.0    0.0   1.0   0.0  134.0    0.0  ...   
1       0.0   0.0   0.0   0.0    0.0   73.0   0.0   0.0    0.0    0.0  ...   
2       0.0   0.0   0.0   0.0    0.0  122.0   1.0   0.0    0.0    0.0  ...   
3       0.0   0.0   0.0   0.0    0.0    9.0   0.0   0.0    0.0    0.0  ...   
4       0.0   0.0   0.0   0.0    0.0    0.0   1.0   6.0    0.0    0.0  ...   
...     ...   ...   ...   ...    ...    ...   ...   ...    ...    ...  ...   
34995   0.0   0.0   0.0   0.0    0.0  148.0   1.0   0.0    0.0    0.0  ...   
34996   0.0   0.0   0.0   0.0    0.0  219.0   1.0   0.0    0.0    0.0  ...   
34997   0.0   0.0   0.0   0.0    0.0    9.0   0.0   0.0    0.0    0.0  ...   
34998   0.0   0.0   0.0   0.0    0.0  111.0   1.0   0.0    0.0    0.0  ...   
34999   0.0   0.0   0.0   0.0    0.0    3.0   0.0   0.0    0.0    0.0  ...   

       Var220  Var221  Var222  Var223  Var224  Var225  Var226  Var227  Var228  \
0      2606.0     4.0  1781.0     0.0     0.0     0.0    19.0     2.0     7.0   
1      3251.0     3.0  2892.0     0.0     0.0     0.0    13.0     4.0     7.0   
2      3342.0     4.0  1023.0     0.0     0.0     0.0     9.0     2.0     7.0   
3      3561.0     4.0  1354.0     3.0     0.0     1.0    12.0     2.0     2.0   
4      2949.0     4.0  3407.0     0.0     0.0     0.0     7.0     2.0     7.0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
34995   310.0     6.0  2336.0     0.0     0.0     0.0     9.0     3.0    13.0   
34996  2003.0     4.0   227.0     0.0     0.0     0.0     7.0     2.0     7.0   
34997  2379.0     4.0  1196.0     0.0     0.0     0.0    10.0     2.0     7.0   
34998   310.0     2.0  2336.0     3.0     0.0     0.0    10.0     3.0     9.0   
34999   643.0     4.0   451.0     0.0     0.0     0.0    12.0     2.0     7.0   

       Var229  
0         0.0  
1         0.0  
2         0.0  
3         1.0  
4         0.0  
...       ...  
34995     0.0  
34996     0.0  
34997     0.0  
34998     1.0  
34999     0.0  

[35000 rows x 212 columns]

In [222]:
tmp = oe.transform(df_test)
tmp1 = pd.DataFrame(tmp, columns=cols)

In [223]:
tmp1

Var1  Var2  Var3  Var4  Var5    Var6  Var7  Var9  Var10  Var11  ...  \
0      0.0   0.0   0.0   0.0   0.0  1225.0  -1.0   0.0    0.0   -1.0  ...   
1      0.0   0.0   0.0   0.0   0.0   896.0  -1.0   0.0    0.0   -1.0  ...   
2      0.0   0.0   0.0   0.0   0.0   791.0  -1.0   0.0    0.0   -1.0  ...   
3      0.0   0.0   0.0   0.0   0.0    -1.0  -1.0   0.0    0.0   -1.0  ...   
4      8.0   0.0   0.0   0.0   0.0     0.0  -1.0  28.0    0.0   -1.0  ...   
...    ...   ...   ...   ...   ...     ...   ...   ...    ...    ...  ...   
9995   0.0   0.0   0.0   0.0   0.0   714.0  -1.0   0.0    0.0   -1.0  ...   
9996   0.0   0.0   0.0   0.0   0.0   812.0  -1.0   0.0    0.0   -1.0  ...   
9997   0.0   0.0   0.0   0.0   0.0   819.0  -1.0   0.0    0.0   -1.0  ...   
9998   0.0   0.0   0.0   0.0   0.0     0.0  -1.0   0.0    0.0   -1.0  ...   
9999   0.0   0.0   0.0   0.0   0.0   868.0  -1.0   0.0    0.0   -1.0  ...   

      Var220  Var221  Var222  Var223  Var224  Var225  Var226  Var227  Var228  \
0       -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0   
1       -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0   
2       -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0   
3       -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0   
4       -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
9995    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0   
9996    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0   
9997    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0   
9998    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0   
9999    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0   

      Var229  
0       -1.0  
1       -1.0  
2       -1.0  
3       -1.0  
4       -1.0  
...      ...  
9995    -1.0  
9996    -1.0  
9997    -1.0  
9998    -1.0  
9999    -1.0  

[10000 rows x 212 columns]