In [ ]:
# !unzip data.zip

In [ ]:
# !pip3 install --upgrade pandas

In [ ]:
import warnings
warnings.filterwarnings('ignore')

# Входные данные

In [ ]:
import pandas as pd
import os
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder
from sklearn.impute import SimpleImputer
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.pipeline import Pipeline
from sklearn.compose import make_column_selector as selector, ColumnTransformer

PATH_TO_DATA = 'data'

In [ ]:
df = pd.read_csv(os.path.join(PATH_TO_DATA, 'orange_small_churn_data.train'))
y = pd.read_csv(os.path.join(PATH_TO_DATA, 'orange_small_churn_labels.train'), header=None, squeeze=True)

In [ ]:
df.shape, y.shape

((40000, 230), (40000,))

In [ ]:
class NanColumnsDropper(BaseEstimator, TransformerMixin):
    def __init(self):
        super().__init__()

    def fit(self, X):
        self.nan_cols = X.loc[:, X.isna().all()].columns
        return self

    def transform(self, X):
        X_transformed = X.drop(self.nan_cols, axis=1)
        self.cols = X_transformed.columns
        return X_transformed

In [ ]:
import sklearn

sklearn.__version__

'0.22.2.post1'

In [ ]:
numeric_transformer = SimpleImputer(strategy='most_frequent')

categorical_transformer = Pipeline([
    ('simple_imputer', SimpleImputer(strategy='most_frequent')),
    ('ordinal_encoder', OrdinalEncoder())
])

preprocessor = ColumnTransformer(transformers=[
    ('num', numeric_transformer, selector(dtype_exclude="object")),
    ('cat', categorical_transformer, selector(dtype_include="object"))
])

preprocessor_pipeline = Pipeline([
    ('nan_columns_dropper', NanColumnsDropper()),
    ('preprocessor', preprocessor)
])

In [ ]:
# Отделим hold-out dataset
df_train, df_ho, y_train, y_valid = train_test_split(df, y, test_size=5000)
# df_train_ho.to_csv(os.path.join(PATH_TO_DATA, 'hold_out_train_dataset.csv'))

In [ ]:
%%time
X_train = preprocessor_pipeline.fit_transform(df_train)

CPU times: user 6.08 s, sys: 227 ms, total: 6.3 s
Wall time: 6.29 s


In [ ]:
X_train = pd.DataFrame(X_train, columns=preprocessor_pipeline['nan_columns_dropper'].cols).astype('int')
X_train

Var1  Var2  Var3  Var4  Var5  ...  Var225  Var226  Var227  Var228  Var229
0         0     0     0     0     0  ...       0      18       2       7       0
1         0     0     0     0     0  ...       0      14       2       2       0
2         0     0     0     0     0  ...       0       9       2       7       1
3         0     0     0     0     0  ...       0      13       1      18       0
4         0     0     0     0     0  ...       0      13       2       7       0
...     ...   ...   ...   ...   ...  ...     ...     ...     ...     ...     ...
34995     0     0     0     0     0  ...       0       5       0       7       0
34996     0     0     0     0     0  ...       1       1       2       7       0
34997     0     0     0     0     0  ...       0      10       2       7       0
34998     0     0     0     0     0  ...       0      10       2       7       0
34999     0     0     0     0     0  ...       1      12       2       7       0

[35000 rows x 212 columns]

In [ ]:
%%time
X_valid = preprocessor_pipeline.fit_transform(df_ho)

CPU times: user 375 ms, sys: 1.79 ms, total: 377 ms
Wall time: 380 ms


In [ ]:
X_valid = pd.DataFrame(X_valid, columns=preprocessor_pipeline['nan_columns_dropper'].cols).astype('int')
X_valid

Var1  Var2  Var3  Var4  Var5  ...  Var225  Var226  Var227  Var228  Var229
0        0     0     0     0     0  ...       1      22       2       2       1
1        0     0     0     0     0  ...       1      19       2       8       0
2        0     0     0     0     0  ...       1      20       3      15       0
3        0     0     0     0     0  ...       1       7       2       8       0
4        0     0     0     0     0  ...       0       2       2       8       0
...    ...   ...   ...   ...   ...  ...     ...     ...     ...     ...     ...
4995     0     0     0     0     0  ...       2      12       2       8       0
4996     0     0     0     0     0  ...       0       7       3       8       0
4997     0     0     0     0     0  ...       1       4       3      10       1
4998     0     0     0     0     0  ...       0       3       2       8       0
4999     0     0     0     0     0  ...       0       7       2       8       0

[5000 rows x 212 columns]

# Модель

In [ ]:
from sklearn.model_selection import cross_val_score, StratifiedShuffleSplit
from sklearn.linear_model import RidgeClassifier, LogisticRegression, SGDClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import classification_report, roc_auc_score

In [ ]:
cv = StratifiedShuffleSplit(n_splits=8, random_state=2179)

## LogisticRegression

In [ ]:
lr_cv = cross_val_score(estimator=LogisticRegression(random_state=2179), X=X_train, y=y_train, cv=cv, n_jobs=-1, scoring='roc_auc')
lr_cv, lr_cv.mean()

(array([0.49043329, 0.51152184, 0.49272436, 0.51360161, 0.48530627,
        0.51666667, 0.49531339, 0.47154558]), 0.497139126305793)

In [ ]:
lr_cv = cross_val_score(estimator=LogisticRegression(random_state=2179), X=X_train, y=y_train, cv=cv, n_jobs=-1, scoring='f1')
lr_cv, lr_cv.mean()

(array([0.00746269, 0.02264151, 0.        , 0.01428571, 0.        ,
        0.02230483, 0.        , 0.        ]), 0.008336842875074423)

In [ ]:
lr_cv = cross_val_score(estimator=LogisticRegression(random_state=2179), X=X_train, y=y_train, cv=cv, n_jobs=-1, scoring='precision')
lr_cv, lr_cv.mean()

(array([0.125     , 0.6       , 0.        , 0.1       , 0.        ,
        0.33333333, 0.        , 0.        ]), 0.14479166666666665)

In [ ]:
lr_cv = cross_val_score(estimator=LogisticRegression(random_state=2179), X=X_train, y=y_train, cv=cv, n_jobs=-1, scoring='recall')
lr_cv, lr_cv.mean()

(array([0.00384615, 0.01153846, 0.        , 0.00769231, 0.        ,
        0.01153846, 0.        , 0.        ]), 0.004326923076923077)

In [ ]:
logistic_regression = LogisticRegression(random_state=2179)
logistic_regression.fit(X_train, y_train)
print(classification_report(y_valid, logistic_regression.predict(X_valid)))

              precision    recall  f1-score   support

          -1       0.92      0.99      0.96      4620
           1       0.07      0.01      0.01       380

    accuracy                           0.92      5000
   macro avg       0.50      0.50      0.49      5000
weighted avg       0.86      0.92      0.88      5000



In [ ]:
roc_auc_score(y_valid, logistic_regression.predict_proba(X_valid)[:, 1])

0.5072818409660514

## RidgeClassifier

In [ ]:
scores = cross_val_score(estimator=RidgeClassifier(random_state=2179), X=X_train, y=y_train, cv=cv, n_jobs=-1, scoring='roc_auc')
scores, scores.mean()

(array([0.52948362, 0.49871557, 0.51535494, 0.5028312 , 0.49508547,
        0.5234283 , 0.50317901, 0.50207858]), 0.508769586894587)

In [ ]:
scores = cross_val_score(estimator=RidgeClassifier(random_state=2179), X=X_train, y=y_train, cv=cv, n_jobs=-1, scoring='f1')
scores, scores.mean()

(array([0., 0., 0., 0., 0., 0., 0., 0.]), 0.0)

In [ ]:
scores = cross_val_score(estimator=RidgeClassifier(random_state=2179), X=X_train, y=y_train, cv=cv, n_jobs=-1, scoring='precision')
scores, scores.mean()

(array([0., 0., 0., 0., 0., 0., 0., 0.]), 0.0)

In [ ]:
scores = cross_val_score(estimator=RidgeClassifier(random_state=2179), X=X_train, y=y_train, cv=cv, n_jobs=-1, scoring='recall')
scores, scores.mean()

(array([0., 0., 0., 0., 0., 0., 0., 0.]), 0.0)

In [ ]:
ridge_classifier = RidgeClassifier(random_state=2179)
ridge_classifier.fit(X_train, y_train)
print(classification_report(y_valid, ridge_classifier.predict(X_valid)))

              precision    recall  f1-score   support

          -1       0.92      1.00      0.96      4620
           1       0.00      0.00      0.00       380

    accuracy                           0.92      5000
   macro avg       0.46      0.50      0.48      5000
weighted avg       0.85      0.92      0.89      5000



In [ ]:
roc_auc_score(y_valid, ridge_classifier.predict(X_valid))

0.4998917748917749

## SGDClassifier

In [ ]:
scores = cross_val_score(estimator=SGDClassifier(random_state=2179), X=X_train, y=y_train, cv=cv, n_jobs=-1, scoring='roc_auc')
scores, scores.mean()

(array([0.47383428, 0.49110399, 0.48300214, 0.50762346, 0.49751068,
        0.47952754, 0.54152184, 0.46434117]), 0.49230813746438745)

In [ ]:
scores = cross_val_score(estimator=SGDClassifier(random_state=2179), X=X_train, y=y_train, cv=cv, n_jobs=-1, scoring='f1')
scores, scores.mean()

(array([0.02402402, 0.02247191, 0.02076125, 0.14285714, 0.06940063,
        0.0212766 , 0.14074318, 0.00704225]), 0.05607212242944377)

In [ ]:
scores = cross_val_score(estimator=SGDClassifier(random_state=2179), X=X_train, y=y_train, cv=cv, n_jobs=-1, scoring='precision')
scores, scores.mean()

(array([0.05479452, 0.42857143, 0.10344828, 0.07788595, 0.19298246,
        0.13636364, 0.07695074, 0.04166667]), 0.13908295925113856)

In [ ]:
scores = cross_val_score(estimator=SGDClassifier(random_state=2179), X=X_train, y=y_train, cv=cv, n_jobs=-1, scoring='recall')
scores, scores.mean()

(array([0.01538462, 0.01153846, 0.01153846, 0.86153846, 0.04230769,
        0.01153846, 0.82307692, 0.00384615]), 0.22259615384615383)

In [ ]:
sgd_classifier = SGDClassifier(random_state=2179)
sgd_classifier.fit(X_train, y_train)
print(classification_report(y_valid, sgd_classifier.predict(X_valid)))

              precision    recall  f1-score   support

          -1       0.92      0.99      0.95      4620
           1       0.07      0.01      0.02       380

    accuracy                           0.91      5000
   macro avg       0.50      0.50      0.49      5000
weighted avg       0.86      0.91      0.88      5000



In [ ]:
roc_auc_score(y_valid, sgd_classifier.predict(X_valid))

0.49954431533378896

### SGDClassifier log loss

In [ ]:
scores = cross_val_score(estimator=SGDClassifier(random_state=2179, loss='log'), X=X_train, y=y_train, cv=cv, n_jobs=-1, scoring='roc_auc')
scores, scores.mean()

(array([0.47241216, 0.49109568, 0.48705722, 0.51331315, 0.48114672,
        0.49047483, 0.53507004, 0.47027184]), 0.492605205365622)

In [ ]:
scores = cross_val_score(estimator=SGDClassifier(random_state=2179, loss='log'), X=X_train, y=y_train, cv=cv, n_jobs=-1, scoring='f1')
scores, scores.mean()

(array([0.00675676, 0.01515152, 0.01398601, 0.13636364, 0.02013423,
        0.12959912, 0.13815575, 0.01413428]), 0.05928516231063527)

In [ ]:
scores = cross_val_score(estimator=SGDClassifier(random_state=2179, loss='log'), X=X_train, y=y_train, cv=cv, n_jobs=-1, scoring='precision')
scores, scores.mean()

(array([0.02777778, 0.5       , 0.07692308, 0.07577055, 0.07894737,
        0.07559257, 0.0754717 , 0.08695652]), 0.12467994497319529)

In [ ]:
scores = cross_val_score(estimator=SGDClassifier(random_state=2179, loss='log'), X=X_train, y=y_train, cv=cv, n_jobs=-1, scoring='recall')
scores, scores.mean()

(array([0.00384615, 0.00769231, 0.00769231, 0.68076923, 0.01153846,
        0.45384615, 0.81538462, 0.00769231]), 0.24855769230769229)

In [ ]:
sgd_classifier_log = SGDClassifier(random_state=2179, loss='log')
sgd_classifier_log.fit(X_train, y_train)
print(classification_report(y_valid, sgd_classifier_log.predict(X_valid)))

              precision    recall  f1-score   support

          -1       0.92      0.97      0.95      4620
           1       0.05      0.02      0.03       380

    accuracy                           0.90      5000
   macro avg       0.49      0.49      0.49      5000
weighted avg       0.86      0.90      0.88      5000



In [ ]:
roc_auc_score(y_valid, sgd_classifier_log.predict_proba(X_valid)[:, 1])

0.4949419002050581

## RandomForestClassifier

In [ ]:
random_forest_classifier = RandomForestClassifier(oob_score=True, random_state=2179)
random_forest_classifier.fit(X_train, y_train)
random_forest_classifier.oob_score_

0.9257714285714286

In [ ]:
scores = cross_val_score(estimator=RandomForestClassifier(random_state=2179), X=X_train, y=y_train, cv=cv, n_jobs=-1, scoring='roc_auc')
scores, scores.mean()

(array([0.50492521, 0.49879511, 0.50411681, 0.48576923, 0.49585411,
        0.50802825, 0.50597994, 0.488934  ]), 0.4990503323836657)

In [ ]:
scores = cross_val_score(estimator=RandomForestClassifier(random_state=2179), X=X_train, y=y_train, cv=cv, n_jobs=-1, scoring='f1')
scores, scores.mean()

(array([0., 0., 0., 0., 0., 0., 0., 0.]), 0.0)

In [ ]:
scores = cross_val_score(estimator=RandomForestClassifier(random_state=2179), X=X_train, y=y_train, cv=cv, n_jobs=-1, scoring='precision')
scores, scores.mean()

(array([0., 0., 0., 0., 0., 0., 0., 0.]), 0.0)

In [ ]:
scores = cross_val_score(estimator=RandomForestClassifier(random_state=2179), X=X_train, y=y_train, cv=cv, n_jobs=-1, scoring='recall')
scores, scores.mean()

(array([0., 0., 0., 0., 0., 0., 0., 0.]), 0.0)

In [ ]:
print(classification_report(y_valid, random_forest_classifier.predict(X_valid)))

              precision    recall  f1-score   support

          -1       0.92      1.00      0.96      4620
           1       0.00      0.00      0.00       380

    accuracy                           0.92      5000
   macro avg       0.46      0.50      0.48      5000
weighted avg       0.85      0.92      0.89      5000



In [ ]:
roc_auc_score(y_valid, random_forest_classifier.predict_proba(X_valid)[:, 1])

0.4870050125313284

## GradientBoostingClassifier

In [ ]:
%%time
scores = cross_val_score(estimator=GradientBoostingClassifier(random_state=2179), X=X_train, y=y_train, cv=cv, n_jobs=-1, scoring='roc_auc')
print(scores, scores.mean())

[0.49398089 0.49778668 0.53405686 0.51250119 0.49747151 0.52226377
 0.51896011 0.50801401] 0.510629377374169
CPU times: user 866 ms, sys: 134 ms, total: 1 s
Wall time: 4min 24s


In [ ]:
scores = cross_val_score(estimator=GradientBoostingClassifier(random_state=2179), X=X_train, y=y_train, cv=cv, n_jobs=-1, scoring='f1')
scores, scores.mean()

(array([0.00763359, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ]), 0.0009541984732824428)

In [103]:
scores = cross_val_score(estimator=GradientBoostingClassifier(random_state=2179), X=X_train, y=y_train, cv=cv, n_jobs=-1, scoring='precision')
scores, scores.mean()

(array([0.5, 0. , 0. , 0. , 0. , 0. , 0. , 0. ]), 0.0625)

In [104]:
scores = cross_val_score(estimator=GradientBoostingClassifier(random_state=2179), X=X_train, y=y_train, cv=cv, n_jobs=-1, scoring='recall')
scores, scores.mean()

(array([0.00384615, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ]), 0.0004807692307692308)

In [ ]:
gb_classifier = GradientBoostingClassifier(random_state=2179)
gb_classifier.fit(X_train, y_train)
print(classification_report(y_valid, gb_classifier.predict(X_valid)))

              precision    recall  f1-score   support

          -1       0.92      1.00      0.96      4620
           1       0.00      0.00      0.00       380

    accuracy                           0.92      5000
   macro avg       0.46      0.50      0.48      5000
weighted avg       0.85      0.92      0.89      5000



In [ ]:
roc_auc_score(y_valid, gb_classifier.predict_proba(X_valid)[:, 1])

0.501481259968102

# Тест

In [ ]:
def write_to_submission_file(predicted_labels, out_file,
                             target='result', index_label="id"):
    # turn predictions into data frame and save as csv file
    predicted_df = pd.DataFrame(predicted_labels,
                                index = np.arange(0, predicted_labels.shape[0]),
                                columns=[target])
    predicted_df.to_csv(out_file, index_label=index_label)

In [ ]:
df_test = pd.read_csv(os.path.join(PATH_TO_DATA, 'orange_small_churn_test_data.csv'), index_col=0)
df_test

Var1  Var2  Var3  Var4  ...  Var227            Var228  Var229  Var230
ID                            ...                                          
0      NaN   NaN   NaN   NaN  ...    6fzt           Zy3gnGM     NaN     NaN
1      NaN   NaN   NaN   NaN  ...    RAYp     F2FyR07IdsN7I     NaN     NaN
2      NaN   NaN   NaN   NaN  ...    RAYp     F2FyR07IdsN7I    mj86     NaN
3      NaN   NaN   NaN   NaN  ...    RAYp     F2FyR07IdsN7I    am7c     NaN
4      8.0   NaN   NaN   NaN  ...    RAYp     F2FyR07IdsN7I     NaN     NaN
...    ...   ...   ...   ...  ...     ...               ...     ...     ...
9995   NaN   NaN   NaN   NaN  ...    ZI9m  R4y5gQQWY8OodqDV    am7c     NaN
9996   NaN   NaN   NaN   NaN  ...    RAYp           55YFVY9    mj86     NaN
9997   NaN   NaN   NaN   NaN  ...    RAYp           55YFVY9    am7c     NaN
9998   NaN   NaN   NaN   NaN  ...    RAYp           55YFVY9     NaN     NaN
9999   NaN   NaN   NaN   NaN  ...    RAYp     F2FyR07IdsN7I    mj86     NaN

[10000 rows x 230 columns]

In [ ]:
%%time
X_test = preprocessor_pipeline.fit_transform(df_test)

CPU times: user 994 ms, sys: 15.3 ms, total: 1.01 s
Wall time: 1.19 s


In [ ]:
X_test = pd.DataFrame(X_test, columns=preprocessor_pipeline['nan_columns_dropper'].cols).astype('int')
X_test

Var1  Var2  Var3  Var4  Var5  ...  Var225  Var226  Var227  Var228  Var229
0        0     0     0     0     0  ...       0      22       1      18       0
1        0     0     0     0     0  ...       0      22       2       8       0
2        0     0     0     0     0  ...       1      17       2       8       1
3        0     0     0     0     0  ...       1      17       2       8       0
4        8     0     0     0     0  ...       0       4       2       8       0
...    ...   ...   ...   ...   ...  ...     ...     ...     ...     ...     ...
9995     0     0     0     0     0  ...       0      22       3      11       0
9996     0     0     0     0     0  ...       0      12       2       2       1
9997     0     0     0     0     0  ...       0      11       2       2       0
9998     0     0     0     0     0  ...       0      19       2       2       0
9999     0     0     0     0     0  ...       0      16       2       8       1

[10000 rows x 212 columns]

In [ ]:
prediction = logistic_regression.predict_proba(X_test)

In [ ]:
write_to_submission_file(prediction[:, 1], 'result.csv')